# Configuration settings for html-proofer.
# For configuration documentation, refer to: https://github.com/gjtorikian/html-proofer#configuration
# For configuration defaults, refer to: https://github.com/gjtorikian/html-proofer/blob/master/lib/html-proofer/configuration.rb
#
html-proofer:
  :disable_external: true
  :only_4xx: true
  :checks_to_ignore:
  - ImageCheck
  - ScriptCheck
  :allow_hash_ref: true
  :error_sort: :desc
  :parallel:
    :in_processes: 3
  :file_ignore:
  - !ruby/regexp /include/
  - !ruby/regexp /page-builder/
  - !ruby/regexp /404.html/
  - !ruby/regexp /action-groups.html/
  - !ruby/regexp /cloud-fastly.html/
  - !ruby/regexp /codelinks/
  - !ruby/regexp /contributing.html/
  - !ruby/regexp /css-preprocess.html/
  - !ruby/regexp /es-overview.html/
  - !ruby/regexp /guides\/m1x/
  - !ruby/regexp /template\.html/
  - !ruby/regexp /videos/
  - !ruby/regexp /whats-new\.html/
  :url_ignore:
  - !ruby/regexp /page-builder/
  - !ruby/regexp /guides\/v2.3/
